application: trendquiz
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /game
  static_dir: game

- url: /game_data
  static_dir: game_data

- url: /data
  static_dir: data

- url: /scripts
  static_dir: scripts

- url: /themes
  static_dir: themes

- url: /images
  static_dir: images

- url: /legacy
  static_dir: legacy

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: trendquiz.py

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?\.html$
